# Generated by Django 5.1.5 on 2025-04-15 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('profile_image', models.ImageField(blank=True, upload_to='')),
                ('favorite_coffee_bags', models.ManyToManyField(blank=True, to='project.coffeebag')),
                ('reviews', models.ManyToManyField(blank=True, to='project.review')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coffee_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
