# Generated by Django 5.1.5 on 2025-04-17 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_review_user_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='tags',
            new_name='tag',
        ),
    ]
