# Generated by Django 5.1.5 on 2025-04-17 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_rename_tags_tag_rename_tags_tag_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffeebag',
            name='name',
        ),
    ]
