# Generated by Django 5.1.5 on 2025-04-24 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_rename_profile_coffeeenthusiast'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='coffeeenthusiast',
            name='email',
        ),
        migrations.RemoveField(
            model_name='coffeeenthusiast',
            name='name',
        ),
        migrations.RemoveField(
            model_name='coffeeenthusiast',
            name='reviews',
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1),
        ),
    ]
