# Generated by Django 5.1.5 on 2025-05-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_rename_tag_tag_name_remove_coffeeenthusiast_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeebag',
            name='tags',
            field=models.ManyToManyField(blank=True, through='project.CoffeeBagTag', to='project.tag'),
        ),
    ]
